import type { Customer } from "@/types/portal";

const customerSeeds = [
  ["Auto Color NS", "Novi Sad", "Vojvodina", "usr-marko", "Marko Petrović", "aktivan", "ključni"],
  ["Lak Centar Dunav", "Beograd", "Beograd", "usr-nenad", "Nenad Simić", "aktivan", "ključni"],
  ["Karoserija Plus", "Inđija", "Vojvodina", "usr-marko", "Marko Petrović", "nov", "razvojni"],
  ["M-Profi Lak", "Niš", "Južna Srbija", "usr-luka", "Luka Nikolić", "u padu", "standard"],
  ["Auto Stil 021", "Veternik", "Vojvodina", "usr-marko", "Marko Petrović", "aktivan", "standard"],
  ["Kolor Servis Šumadija", "Kragujevac", "Centralna Srbija", "usr-ana", "Ana Ristić", "blokiran", "rizični"],
  ["AS Metalik", "Subotica", "Vojvodina", "usr-marko", "Marko Petrović", "aktivan", "standard"],
  ["Balkan Refinish", "Čačak", "Zapadna Srbija", "usr-tamara", "Tamara Kovač", "u padu", "ključni"],
  ["Spektar Auto", "Zemun", "Beograd", "usr-nenad", "Nenad Simić", "aktivan", "standard"],
  ["Lak Komerc", "Pančevo", "Vojvodina", "usr-marko", "Marko Petrović", "neaktivan", "standard"],
  ["Pro Finish Užice", "Užice", "Zapadna Srbija", "usr-tamara", "Tamara Kovač", "aktivan", "razvojni"],
  ["Duga Color", "Leskovac", "Južna Srbija", "usr-luka", "Luka Nikolić", "nov", "razvojni"],
  ["Euro Lak Sistem", "Smederevo", "Centralna Srbija", "usr-ana", "Ana Ristić", "aktivan", "ključni"],
  ["Panel Master", "Ruma", "Vojvodina", "usr-marko", "Marko Petrović", "aktivan", "standard"],
  ["Refinish Partner Istok", "Zaječar", "Centralna Srbija", "usr-ana", "Ana Ristić", "u padu", "rizični"],
] as const;

const statusOf = (value: string): Customer["status"] => value as Customer["status"];
const segmentOf = (value: string): Customer["segment"] => value as Customer["segment"];

export const customers: Customer[] = customerSeeds.map((seed, index) => {
  const [companyName, city, region, salesRepId, salesRepName, status, segment] = seed;
  const debt = index % 5 === 0 ? 620000 + index * 31000 : index % 3 === 0 ? 175000 + index * 14000 : 24000 + index * 6700;
  const creditLimit = index % 5 === 0 ? 500000 : 320000 + index * 18000;
  const revenue365d = 1450000 + index * 415000;
  const trendPercent = status === "u padu" ? -(18 + index) : status === "nov" ? 100 : 4 + (index % 12);
  const lastOrderDay = status === "neaktivan" ? 91 : status === "u padu" ? 54 + index : 3 + index * 2;
  return {
    id: `cus-${index + 1}`,
    code: `K-${String(1001 + index).padStart(5, "0")}`,
    bizniSoftCode: index % 7 === 0 ? undefined : `BS-K-${2200 + index}`,
    companyName,
    legalName: `${companyName} ${index % 2 === 0 ? "DOO" : "PR"}`,
    pib: `${108234560 + index * 137}`,
    registrationNumber: `${21400500 + index * 43}`,
    vatStatus: index % 6 === 0 ? "van PDV sistema" : "PDV obveznik",
    legalForm: index % 2 === 0 ? "DOO" : "Preduzetnik",
    industry: "Održavanje i popravka motornih vozila",
    cooperationSince: `${2013 + (index % 11)}-${String(1 + (index % 9)).padStart(2, "0")}-12`,
    status: statusOf(status),
    segment: segmentOf(segment),
    size: index % 4 === 0 ? "veliki" : index % 3 === 0 ? "mali" : "srednji",
    region,
    city,
    website: index % 4 === 0 ? `https://${companyName.toLowerCase().replace(/[^a-z0-9]+/g, "")}.rs` : undefined,
    source: ["preporuka", "teren", "partner mreža", "sajam"][index % 4],
    salesRepId,
    salesRepName,
    contacts: [
      {
        id: `con-${index + 1}-1`,
        name: ["Nikola Pavlović", "Stefan Matić", "Milica Đorđević", "Aleksandar Kostić"][index % 4],
        role: index % 2 === 0 ? "Vlasnik" : "Nabavka",
        phone: `+381 6${index % 5 + 3} ${String(201100 + index * 311)}`,
        email: `nabavka@${companyName.toLowerCase().replace(/[^a-z0-9]+/g, "")}.rs`,
        preferredChannel: ["telefon", "Viber", "email", "WhatsApp"][index % 4] as Customer["contacts"][number]["preferredChannel"],
        contactWindow: "Radnim danima 08:00–15:00",
      },
    ],
    addresses: [
      {
        id: `adr-${index + 1}-1`,
        type: "isporuka",
        street: index === 5 ? "Industrijska zona bb" : `${["Industrijska", "Novosadska", "Cara Dušana", "Bulevar oslobođenja"][index % 4]} ${12 + index}`,
        city,
        postalCode: index === 5 ? "" : String(11000 + index * 420),
        contactName: ["Nikola", "Stefan", "Milica"][index % 3],
        phone: index === 11 ? "" : `+381 6${index % 5 + 3} ${String(201100 + index * 311)}`,
        deliveryNote: index % 3 === 0 ? "Pozvati 30 minuta pre isporuke" : undefined,
        access: index % 4 === 0 ? "Pristup kombijem, bez šlepera" : "Pristup kombijem i kamionom",
        receivingHours: "08:00–14:00",
        complete: index !== 5 && index !== 11,
      },
      ...(index % 5 === 0 ? [{
        id: `adr-${index + 1}-2`, type: "fakturisanje" as const, street: `Glavna ${30 + index}`, city, postalCode: String(11000 + index * 420), complete: true,
      }] : []),
    ],
    priceList: index % 3 === 0 ? "PRO partner" : index % 3 === 1 ? "Standard B2B" : "Razvojni kupac",
    baseDiscount: 8 + (index % 5) * 2,
    paymentTermDays: [15, 30, 45, 60][index % 4],
    paymentMethod: index % 4 === 0 ? "avansno" : "virman",
    freeDelivery: index % 3 !== 0,
    minimumOrderValue: 12000,
    specialTerms: index % 4 === 0 ? "Posebna cena za R-M bezbojne lakove" : undefined,
    specialTermsExpiresAt: index % 4 === 0 ? "2026-09-30" : undefined,
    financial: {
      debt,
      overdueDebt: index % 3 === 0 ? Math.round(debt * 0.58) : Math.round(debt * 0.16),
      notDueDebt: index % 3 === 0 ? Math.round(debt * 0.42) : Math.round(debt * 0.84),
      oldestDebtDays: index % 5 === 0 ? 74 : 8 + index,
      averageDelayDays: index % 5 === 0 ? 32 : 3 + (index % 10),
      maxDelayDays: index % 5 === 0 ? 78 : 12 + index,
      creditLimit,
      creditUsed: debt,
      averageOrderValue: 42000 + index * 4800,
      revenue30d: 98000 + index * 25000,
      revenue90d: 315000 + index * 71000,
      revenue365d,
      previousYearRevenue: Math.round(revenue365d / (1 + trendPercent / 100 || 1)),
      grossMargin: Math.round(revenue365d * (0.19 + (index % 6) * 0.008)),
      averageMargin: 19 + (index % 7),
      profitability: 14 + (index % 8),
      deliveryCost: 28000 + index * 1900,
      estimatedNetValue: Math.round(revenue365d * 0.15),
    },
    sales: {
      orderCount: 18 + index * 6,
      lastOrderAt: `2026-${lastOrderDay > 60 ? "05" : "07"}-${String(2 + (index % 24)).padStart(2, "0")}`,
      daysSinceLastOrder: lastOrderDay,
      averageOrderGapDays: 14 + (index % 8) * 4,
      favoriteManufacturers: index % 2 === 0 ? ["R-M", "Carsystem"] : ["baslac", "SIA"],
      favoriteGroups: index % 3 === 0 ? ["Bezbojni lakovi", "Učvršćivači"] : ["Brusni materijal", "Gitovi"],
      topProducts: ["C-2P45 Speed Finish-R", "F19 Brusni disk P150"],
      lostProducts: status === "u padu" ? ["R-M Pasta 190", "Cosmos sprej crni mat"] : [],
      trendPercent,
      potential: index % 4 === 0 ? "visok" : index % 3 === 0 ? "nizak" : "srednji",
      shareOfWallet: 32 + (index % 7) * 7,
      nextOpportunity: index % 2 === 0 ? "Uvođenje SIA brusnog programa" : "R-M sistem bezbojnih lakova",
      declineReason: status === "u padu" ? "Konkurentska ponuda i ređe porudžbine" : undefined,
    },
    internal: {
      category: index % 5 === 0 ? "A" : index % 3 === 0 ? "C" : "B",
      strategicImportance: index % 5 === 0 ? "visok" : "srednji",
      risk: debt > creditLimit ? "visok" : index % 3 === 0 ? "srednji" : "nizak",
      paymentReliability: 52 + ((index * 7) % 45),
      negotiationWeight: 45 + ((index * 9) % 48),
      growthPotential: 48 + ((index * 11) % 50),
      churnProbability: status === "u padu" ? 67 : 8 + (index % 4) * 9,
      priceSensitivity: 44 + ((index * 5) % 50),
      relationshipQuality: 58 + ((index * 6) % 40),
      recommendedExposure: Math.round(creditLimit * 0.85),
      minimumMargin: 18 + (index % 4),
      warning: debt > creditLimit ? "Ne odobravati dodatni limit bez plana naplate." : undefined,
      confidentialNote: index % 4 === 0 ? "Vlasnik direktno odlučuje, traži jasan obračun ukupnog efekta." : undefined,
    },
    openOrders: index % 5,
    complaints: index % 6 === 0 ? 1 : 0,
    returns: index % 9 === 0 ? 1 : 0,
    averageProcessingHours: 3 + (index % 5),
    preferredDelivery: index % 3 === 0 ? "Lični prevoz" : "BEX",
    bexDataStatus: index === 5 || index === 11 ? "nepotpuno" : index === 8 ? "greška" : "usklađeno",
    bizniSoftSyncStatus: index % 7 === 0 ? "nije povezano" : index % 6 === 0 ? "neusklađeno" : "usklađeno",
    communicationNote: index % 3 === 0 ? "Preferira kratke poruke sa šifrom i cenom." : undefined,
    aliases: index === 0 ? { "ona sia 150": "prd-22", "crni git 1kg": "prd-30" } : undefined,
  };
});
